#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

test_api:
    path: /test_api
    controller: App\Controller\AuthController::test_api

login_check:
    path:     /login_check
    methods:  [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui